### ISSUE TITLE
Client Example Actually Working?

### ISSUE THREAD

**Issue by willemevenwel** [burke166/blazor-client-side-realworld-example-app#1]
Hi,

Is this client application example actually working? I looked at the server side example, and I can learn a lot, but would like to see the client only implementation. Currently running the client application after checking it out I only see the text "loading..."

(Forgive me I'm very new to Blazor)

Regards,

w

**Comment by burke166** [comment]
Sorry for the late response. Yes, it's working, but the first load is a bit long. Checking with Fiddler, the first load has roughly 40 requests and in total takes anywhere from 5 to 9 seconds on my machine. That's all to download the WebAssembly stuff, which it looks to be at least 5MB. Once you've got that cached, subsequent requests are quick. I'm going to look to see if that can be optimized a little.
